version: "3.7"
services:
  org-node:
    image: gcr.io/radicle-services/org-node:latest
    build:
      dockerfile: ./org-node/Dockerfile
      context: .
    ports:
      - 8776:8776/udp
    volumes:
      - $HOME/.radicle:/app/radicle
    environment:
      RUST_LOG: org-node=debug,info
    init: true
    container_name: org-node
    restart: unless-stopped
    command: ["--orgs", $RADICLE_ORGS, "--subgraph", "https://gateway.thegraph.com/api/1758a78ae257ad4906f9c638e4a68c19/subgraphs/id/0x2f0963e77ca6ac0c2dad1bf4147b6b40e0dd8728-0", "--rpc-url", $ETH_RPC_URL, '--influxdb', 'http://influxdb:8086', '--influxdb-token', $RADICLE_INFLUXDB_TOKEN]
    networks:
      - radicle-services
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: unless-stopped
    networks:
      - radicle-services
    volumes:
      - $HOME/.radicle/influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${RADICLE_INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=radicle
      - DOCKER_INFLUXDB_INIT_BUCKET=client-services
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${RADICLE_INFLUXDB_TOKEN}
  caddy:
    volumes:
      - $PWD/Caddyfile.p2p:/etc/caddy/Caddyfile:ro

networks:
  radicle-services:
    name: radicle-services
