version: "3.7"
services:
  http-api:
    image: gcr.io/radicle-services/http-api:latest
    build:
      dockerfile: ./http-api/Dockerfile
      context: .
    volumes:
      - $HOME/.radicle:/app/radicle:ro
    environment:
      RUST_LOG: info
    init: true
    container_name: http-api
    restart: unless-stopped
    networks:
      - radicle-services
  git-server:
    image: gcr.io/radicle-services/git-server:latest
    build:
      dockerfile: ./git-server/Dockerfile
      context: .
    volumes:
      - $HOME/.radicle:/app/radicle
    environment:
      - RUST_LOG=hyper=warn,debug
    init: true
    container_name: git-server
    restart: unless-stopped
    networks:
      - radicle-services
  caddy:
    image: caddy:2.4.5
    ports:
      - 80:80
      - 443:443
      - 8777:8777
      - 8086:8086
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - RADICLE_DOMAIN=$RADICLE_DOMAIN
    container_name: caddy
    restart: unless-stopped
    networks:
      - radicle-services

networks:
  radicle-services:
    name: radicle-services
